name: suyoapp_com
services:
  suyoapp_com_api:
    image: rg2.vintolab.com/suyoapp_com/api:latest
    container_name: suyoapp_com_api
    restart: unless-stopped
    ports:
      - "10.50.0.2:9051:80"
    env_file:
      - .env/db.env
      - .env/s3bender.env
      - .env/session.env
      - .env/stripe.env
      - .env/smtp.env
      - .env/redis.env
      - .env/iap.env
      - .env/ratelimit.env

  suyoapp_com_admin:
    image: rg2.vintolab.com/suyoapp_com/admin:latest
    container_name: suyoapp_com_admin
    restart: unless-stopped
    ports:
      - "10.50.0.2:9052:80"
    env_file:
      - .env/db.env
      - .env/smtp.env
      - .env/session.env
      - .env/s3bender.env
      - .env/redis.env

  suyoapp_com_webui:
    image: rg2.vintolab.com/suyoapp_com/webui:latest
    container_name: suyoapp_com_webui
    restart: unless-stopped
    ports:
      - "10.50.0.2:9053:80"