name: suyoapp_com
services:
  suyoapp_com_api:
    image: kingeli/suyoapp_com_api:latest
    container_name: suyoapp_com_api
    restart: unless-stopped
    networks:
      - shared-global-network
    env_file:
      - .env/db.env
      - .env/minio.env
      - .env/session.env
      - .env/stripe.env
      - .env/smtp.env
      - .env/redis.env

  suyoapp_com_admin:
    image: kingeli/suyoapp_com_admin:latest
    container_name: suyoapp_com_admin
    restart: unless-stopped
    networks:
      - shared-global-network
    env_file:
      - .env/db.env
      - .env/smtp.env
      - .env/session.env
      - .env/minio.env

  suyoapp_com_webui:
    image: kingeli/suyoapp_com_webui:latest
    container_name: suyoapp_com_webui
    restart: unless-stopped
    networks:
      - shared-global-network

networks:
  shared-global-network:
    external: true