services:
  suyoapp_com_api:
    build: ./api_v1
    volumes:
      - ./api_v1:/app
    command: npm run http-dev
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      - "s3.global.local:host-gateway"
    ports:
      - "2001:80"

  suyoapp_com_admin:
    build: ./admin
    volumes:
      - ./admin:/var/www/html
    extra_hosts:
      - "s3.global.local:host-gateway"

  suyoapp_com_webui:
    build:
      context: ./web_ui
      target: build
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./web_ui:/var/www/html
    ports:
      - "5173:5173"