name: suyoapp_com
services:
  suyoapp_com_api:
    build: ./api
    volumes:
      - ./api:/app
    command: npm run http-dev
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  suyoapp_com_admin:
    build: ./admin
    volumes:
      - ./admin:/var/www/html

  suyoapp_com_webui:
    build:
      context: ./web
      target: build
    command: npm run dev -- --host 0.0.0.0